#!/bin/bash

[ `id -u` -ne 0 ] && echo "This script must be run using sudo!" && exit 1
banner="========================================================================="
banner_short="============================"
header() {
  printf '%s\n' "$banner" "$*" "$banner"
}
header_short() {
  printf '%s\n' "$banner_short" "$*" "$banner_short"
}

bold=$(tput bold)
normal=$(tput sgr0)
red=$(tput setaf 1)
blue=$(tput setaf 4)
yellow=$(tput setaf 3)
green=$(tput setaf 2)

#Welome
echo
header "Welcome to Security Onion Email Configuration!"
echo -e "\nPlease follow the steps below to configure Security Onion email alerts.\n"
echo -e "${yellow}Please note, this script will install mailutils and nullmailer if they are not already installed.${normal}\n"

read -p "Would you like to continue? [y/N]" response
case $response in
        [yY])
                :
                ;;
        *)
                echo -e "\n${red}Exiting...${normal}\n"
		exit 1
                ;;
esac

#Check if mailutils installed.  If not, install it
if dpkg -l | grep -q -i "mailutils"; then
        :
else
        echo -e "\nRequires mailutils..."
	read -p "Do you wish to continue installing mailutils? [y/N]" response
	case $response in
		[yY])
			echo "Installing mailutils..."
			apt-get install -y mailutils > /dev/null
			echo "Done."
			:
			;;
		*)
			exit 1
			;;
	esac
fi

#Check if nullmailer is installed.  If not, install it.
if dpkg -l | grep -q -i "nullmailer"; then
        :
else
        echo -e "\nRequires nullmailer..."
	read -p "Do you wish to continue installing mailutils? [y/N]" response
        case $response in
                [yY])
                        echo "Installing nulmailer..."
                        apt-get install -y nullmailer > /dev/null
                        echo "Done."
			:
                        ;;
                *)
                        exit 1
                        ;;
        esac
fi
echo
header_short "System Mail Configuration"

#Read and configure nullmailer files
mailname=$(cat /etc/mailname)

[ -z $mailname ] && echo -e "\nnullmailer not installed!  Please install using 'apt-get -y nullmailer'.\n"

read -p "Do you wish to keep the FROM address set as '${yellow}$mailname${normal}'? [y/N]" response
case $response in
        [yY])
                :
                ;;
        *)
                echo "What would you like to specify for the FROM address? [ENTER]:"
                read from
                echo $from > /etc/mailname
                ;;
esac
adminaddr=$(cat /etc/nullmailer/adminaddr)
if [[ $adminaddr = "" ]];then
	echo "What would you like to specify for the notification address?"
	read nullmail
	echo $nullmail > /etc/nullmailer/adminaddr
else
	read -p "Do you wish to keep the notification address set as '${yellow}$adminaddr${normal}'? [y/N]" response
	case $response in
		[yY])
			:
			;;
		*)
			echo "What would you like to specify for the notification address?"
			read nullmail
			echo $nullmail > /etc/nullmailer/adminaddr
			;;
	esac
fi
remotes=$(cat /etc/nullmailer/remotes)
read -p "Do you wish to keep the mailserver set to '${yellow}$remotes${normal}'? [y/N]" response
case $response in
        [yY])
                :
                ;;
        *)
                echo "What would you like to specify for the mail server? [ENTER]:"
                read mailserver
                echo $mailserver > /etc/nullmailer/remotes
                ;;
esac

echo
header_short "Configure Daily Sostat Email"

#Configure daily sostat email
gethost=$(hostname)
read -p "Do you wish to configure daily email for sostat output? [y/N]" response
case $response in
        [yY])
                adminaddr=$(cat /etc/nullmailer/adminaddr)
		sostat="/etc/cron.d/sostat"
                rm -f $sostat
                touch $sostat
                echo -e "\n${yellow}Please note, the hostname in the subject line of the email will be configured based off of your current hostname.\nIf you would like to change this, you can manually edit '/etc/cron.d/sostat'. ${normal}\n"
                read -p "Would you like to use '${yellow}$adminaddr${normal}' for the email address? [y/N]" response
                case $response in
                        [yY])
                                somail=$adminaddr
                                ;;
                        *)
                                echo "What would you like to configure the email address as? [Enter]:"
                                read somail
                                ;;
                esac
                echo -e '#/etc/cron.d/sostat\n#\n#crontab entry to run sostat and email its output\n\n\nSHELL=/bin/sh\nPATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin\nEMAIL='$somail'\nHOSTNAME='$gethost'\n\n01 12 * * * root /usr/bin/sostat 2>&1 | mail -s "$HOSTNAME stats" $EMAIL' > $sostat

                ;;
        *)

                :
                ;;
esac

#Configure Bro Email
echo
header_short "Bro Configuration"
read -p "Would you like to configure email for Bro? [y/N]" response
case $response in
        [yY])
                echo -e "\n${yellow}Please note, Bro will restart after configuration is complete.${normal}\n"
		read -p "Would you like to use '${yellow}$adminaddr${normal}' as the notification address? [y/N]" response

                case $response in
                          [yY])
                                bronotify=$adminaddr
                                ;;
                        *)
                                echo "What would you like to configure the Bro notification address as? [ENTER];"
                                read bronotify
                                ;;
                esac
                broctl="/opt/bro/etc/broctl.cfg"
                sed -i "s|^MailTo.*$|MailTo = $bronotify|g" $broctl
                if  grep -q "sendmail" $broctl;then
                        sed -i "s|^sendmail.*$|sendmail = /usr/sbin/sendmail|g" $broctl
                        if grep -q "tracesummary=" $broctl;then
                                sed -i "s|^tracesummary=.*$|tracesummary=|g" $broctl
                        else
                                sed -i '/sendmail/a tracesummary=' $broctl
                        fi
                else
                        sed -i '/MailTo/a\\sendmail = /usr/sbin/sendmail' $broctl
                fi
                localbro="/opt/bro/share/bro/site/local.bro"
                if grep -q -i "email" $localbro;then
                        :
                else
                        echo -e "\n# Bro Notice email configuration\nhook Notice::policy(n: Notice::Info)\n		{       \n      add n\$actions[Notice::ACTION_ALARM];\n		}" >> $localbro
                fi
		#echo -e "\n---------------------------------\nPlease wait while configuring...\n---------------------------------"
		nsm_sensor_ps-restart --only-bro > /dev/null
		echo -e "\nDone."
		;;
        *)
                :
                ;;

esac

#Configure Sguil Email
echo
header_short "Sguil Configuration"
read -p "Would you like to configure Sguil for email alerts? [y/N]" response
case $response in
        [y/Y])
                echo -e "\n${yellow}Please note, sguild will restart when configuration is complete.${normal}\n"
		read -p "Would you like to use '${yellow}$adminaddr${normal}' as the notification address? [y/N]" response

                case $response in
                        [yY])
                                sguilnotify=$adminaddr
                                ;;
                        *)
                                echo "What would you like to configure the Sguil notification address as? [ENTER];"
                                read sguilnotify
                                ;;
                esac
                sguildemail="/etc/nsm/securityonion/sguild.email"
                        sed -i "s|^set EMAIL_EVENTS.*$|set EMAIL_EVENTS 1|g" $sguildemail
                        sed -i "s|^set SMTP.*$|set SMTP_SERVER \"$remotes\"|g" $sguildemail
                        sed -i "s|^set EMAIL_RCPT.*$|set EMAIL_RCPT_TO \"$sguilnotify\"|g" $sguildemail
                        sed -i "s|^set EMAIL_FROM.*$|set EMAIL_FROM \"$gethost\"|g" $sguildemail
                        echo -e "\n---------------------------------\nPlease wait while configuring...\n---------------------------------"
			nsm_server_ps-restart > /dev/null
			echo -e "\nDone."
                ;;
        *)
                :
                ;;
esac

#Configure OSSEC email
echo
header_short "OSSEC Configuration"
read -p "Would you like to configure OSSEC for email alerts? [y/N]" response
case $response in
        [y/Y])
                echo -e "\n${yellow}Please note, OSSEC will restart once configuration is complete.${normal}\n"
		read -p "Would you like to use '${yellow}$adminaddr${normal}' as the notification address? [y/N]" response

                case $response in
                        [yY])
                                remotes=$(cat /etc/nullmailer/remotes)
				ossec_notify=$adminaddr
                                ;;
                        *)
                                echo "What would you like to configure the OSSEC notification address as? [ENTER];"
                                read ossec_notify
                                ;;
                esac
                ossecconf="/var/ossec/etc/ossec.conf"
                if grep -q -i "smtp" $ossecconf;then
                        sed -i 's/.*email_to.*/     <email_to>\'$ossec_notify'\<\/email_to>/' $ossecconf
                        sed -i 's/.*smtp_server.*/     <smtp_server>\'$remotes'\<\/smtp_server>/' $ossecconf
                        sed -i 's/.*email_from.*/     <email_from>\'$gethost'\<\/email_from>/' $ossecconf
                        sed -i 's/.*email_maxperhour.*/     <email_maxperhour>20<\/email_maxperhour>/' $ossecconf
                else
                        sed -i 's/.*email_notification.*/     <email_notification>yes<\/email_notification>/' $ossecconf
                        sed -i '/.*email_notification.*/ a \     <email_to>\'$ossec_notify'\<\/email_to>' $ossecconf
                        sed -i '/.*email_to.*/ a \     <smtp_server>\'$remotes'\<\/smtp_server>' $ossecconf
                        sed -i '/.*smtp_server.*/ a \     <email_from>\ossec@'$gethost'\<\/email_from>' $ossecconf
                        sed -i '/.*email_from.*/ a \     <email_maxperhour>\100\<\/email_maxperhour>' $ossecconf
                fi
			echo -e "\n---------------------------------\nPlease wait while configuring...\n---------------------------------"
			service ossec-hids-server restart > /dev/null
			echo -e "\nDone."
		;;
        *)
                :
                ;;
esac

#Configure ELSA email
echo
header_short "ELSA Configuration"
read -p "Would you like to configure ELSA for email alerts? [y/N]" response
case $response in
        [y/Y])
                echo -e "\n${yellow}Please note, apache2 will restart when configuration is complete.${normal}\n"
		read -p "Would you like to use '${yellow}$adminaddr${normal}' as the notification address? [y/N]" response
		getip=$(hostname -I)
                case $response in
                        [yY])
				elsanotify=$adminaddr
                                echo "What is the ELSA username to which this email address is associated? [ ${yellow}$SUDO_USER${normal}? ]"
                                read user

                                echo "What is the ELSA server IP/hostname for which you wish to alert? [ ${yellow}$getip${normal}? ]"
                                read server
                                ;;
                        *)
                                echo "What would you like to configure the ELSA notification address as?"
                                read elsanotify

				echo "What is the ELSA username to which this email address is associated? [ ${yellow}$SUDO_USER${normal}? ]"
                                read user

                                echo "What is the ELSA server IP/hostname for which you wish to alert? [ ${yellow}$getip${normal}?]"
                                read server
                                ;;
                esac

		elsaweb="/etc/elsa_web.conf"

		mysql -uroot -Dsecurityonion_db -e "update user_info set email='$elsanotify' where username='$user';"
                if grep -q -i "smtp" $elsaweb;then
			sed -i 's#.*base_url.*#    "base_url": "https://'$server'/elsa-query",#g' $elsaweb
			sed -i 's#.*smtp_server.*#    "smtp_server": "'$remotes'",#g' $elsaweb	
		else
			sed -i '/.*"email".*/ a \    "base_url": "https://'$server'/elsa-query",' $elsaweb
			sed -i '/.*base_url.*/ a \    "smtp_server": "'$remotes'",' $elsaweb
		fi
		echo -e "\n---------------------------------\nPlease wait while configuring...\n---------------------------------"
		service apache2 restart 2&>1 > /dev/null
                echo -e "\nDone."
		;;
        *)
                :
                ;;
esac
echo
header "----------------------Email Configuration Complete-----------------------"
echo -e "${green}\nConfiguration is now complete!${normal}\n"
echo -e "If you would like to edit the email configuration manually, please refer to:\n"
echo -e "${green}https://github.com/Security-Onion-Solutions/security-onion/wiki/Email${normal}\n"
