#!/bin/bash
#
#########################################
# Variables
#########################################
DEBUG="0"
HOSTNAME=`hostname`
IP=`ifconfig |grep "inet addr" | awk '{print $2}' |cut -d\: -f2 |grep -v "127.0.0.1" |head -1`
TITLE="Security Onion Email Setup ($HOSTNAME)"
[ -f /etc/postfix/main.cf ] && REMOTE=`grep -o 'relayhost =.*' /etc/postfix/main.cf | cut -f2- -d'='| cut -f2 -d' '` && FROMADDR=`grep -o 'myhostname =.*' /etc/postfix/main.cf | cut -f2- -d'=' | cut -f2 -d' '`
[ -f /etc/aliases ] && ADMINADDR=`grep -o 'root:.*' /etc/aliases | cut -f2- -d' '`
#########################################
# Welcome Screen
#########################################
TEXT="<b>Welcome to Security Onion Email Setup!</b>\n\
\n\
This program will allow you to configure email for Security Onion on $HOSTNAME.\n\
\n\
Please note, this script will install mailutils if it is not already installed.
\n\
Would you like to continue?"
YES="Yes, Continue!"
NO="No, Quit."
zenity --question --title="$TITLE" --text="$TEXT" --ok-label="$YES" --cancel-label="$NO" --no-wrap
ANSWER="$?"
if [ $ANSWER -eq 1 ]; then
        [ $DEBUG -eq 1 ] && echo "DEBUG: Clicked No.  Exiting Setup"
        exit 1
else
        [ $DEBUG -eq 1 ] && echo "DEBUG: Clicked Yes.  Continuing Setup."
fi
#########################################
#'From' Address
#########################################
FROM_CONFIRMED="no"
while [ $FROM_CONFIRMED = "no" ]; do
	TEXT="What would you like to specify for the system's 'From' address?"
	FROMADDRESS=`zenity --title="$TITLE" --text="$TEXT" --entry --entry-text="$FROMADDR"`
	ANSWER="$?"
	if [ $ANSWER -eq 1 ]; then
        	[ $DEBUG -eq 1 ] && echo "DEBUG: Clicked No.  Exiting Setup"
        	exit 1
	else
		if [ -z $FROMADDRESS ]; then 
			zenity --error --title "$TITLE" --text="Please provide a valid response\!"
		else
			[ $DEBUG -eq 1 ] && echo "DEBUG: Clicked Yes.  Configuring 'FROM' address."
			FROM_CONFIRMED="yes"
		fi
	fi
done
#########################################
# Notification Address
#########################################
NOTIFY_CONFIRMED="no"
while [ $NOTIFY_CONFIRMED = "no" ]; do
	TEXT="What would you like to specify for the notification address?"
	NOTIFYADDRESS=`zenity --title="$TITLE" --text="$TEXT" --entry --entry-text="$ADMINADDR"`
	ANSWER="$?"
	if [ $ANSWER -eq 1 ]; then
        	[ $DEBUG -eq 1 ] && echo "DEBUG: Clicked No.  Exiting Setup"
        	exit 1
	else
		if ! [[ "$NOTIFYADDRESS" == ?*@?*.?* ]]; then
                        zenity --error --title "$TITLE" --text="Please provide a valid response\!"
                else
                        [ $DEBUG -eq 1 ] && echo "DEBUG: Clicked Yes.  Configuring notification address."
			NOTIFY_CONFIRMED="yes"
                fi
	fi
done
#########################################
# Mail server
#########################################
MAILSERVER_CONFIRMED="no"
while [ $MAILSERVER_CONFIRMED = "no" ]; do
	TEXT="What address would you like to specify for the mail (SMTP) server?"
	MAILSERVER=`zenity --title="$TITLE" --text="$TEXT" --entry --entry-text="$REMOTE"`
	ANSWER="$?"
	if [ $ANSWER -eq 1 ]; then
        	[ $DEBUG -eq 1 ] && echo "DEBUG: Clicked No.  Exiting Setup"
        	exit 1
	else
		if ! [[ "$MAILSERVER" == ?*.?*.?* ]]; then
                        zenity --error --title "$TITLE" --text="Please provide a valid response\!"
                else
                        [ $DEBUG -eq 1 ] && echo "DEBUG: Clicked Yes.  Configuring SMTP server."
			MAILSERVER_CONFIRMED="yes"
                fi
	fi
done
#########################################
# Sostat email
#########################################
TEXT="Would you like to configure daily email for sostat output?"
YES="Yes"
NO="No"
zenity --question --title="$TITLE" --text="$TEXT" --ok-label="$YES" --cancel-label="$NO" --no-wrap
ANSWER="$?"
if [ $ANSWER -eq 1 ]; then
        [ $DEBUG -eq 1 ] && echo "DEBUG: Clicked No.  Not configuring email for sostat output."
	SOSTATADDRESS="Not Configured"
else
        [  $DEBUG -eq 1 ] && echo "DEBUG: Clicked Yes.  Configuring sostat email."
	#########################################
	# Sostat email address
	#########################################
	SOSTAT_CONFIRMED="yes"
	SOSTATADDRESS="root@localhost"
	#while [ $SOSTAT_CONFIRMED = "no" ]; do
	#	TEXT="What email address would you like to use for daily sostat output?"
	#	SOSTATADDRESS=`zenity --title="$TITLE" --text="$TEXT" --entry --entry-text="$NOTIFYADDRESS"`
	#	ANSWER="$?"
	#	if [ $ANSWER -eq 1 ]; then
	#		[ $DEBUG -eq 1 ] && echo "DEBUG: Clicked Cancel.  Exiting Setup."
	#		exit 1
	#	else
	#		if ! [[ "$SOSTATADDRESS" == ?*@?*.?* ]]; then
         #               	zenity --error --title "$TITLE" --text="Please provide a valid response\!"
          #      	else
	#			[ $DEBUG -eq 1 ] && echo "DEBUG: Clicked OK.  Configuring notification address for sostat."
	#			SOSTAT_CONFIRMED="yes"
	#		fi
	#	fi
	#done
fi
#########################################
# Bro email
#########################################
TEXT="Would you like to configure email alerts for Bro?"
YES="Yes"
NO="No"
zenity --question --title="$TITLE" --text="$TEXT" --ok-label="$YES" --cancel-label="$NO" --no-wrap
ANSWER="$?"
if [ $ANSWER -eq 1 ]; then
        [ $DEBUG -eq 1 ] && echo "DEBUG: Clicked No.  Not configuring email for Bro."
	BROADDRESS="Not Configured"
else
        [ $DEBUG -eq 1 ] && echo "DEBUG: Clicked Yes.  Configuring email for Bro."
	#########################################
        # Bro email address
        #########################################
        BRO_CONFIRMED="yes"
	BROADDRESS="root@localhost"
	#while [ $BRO_CONFIRMED = "no" ]; do
	#	TEXT="What email address would you like to use for Bro alerts?"
	#	BROADDRESS=`zenity --title="$TITLE" --text="$TEXT" --entry --entry-text="$NOTIFYADDRESS"`
        #	ANSWER="$?"
	#	if [ $ANSWER -eq 1 ]; then
	#		[ $DEBUG -eq 1 ] && echo "DEBUG: Clicked Cancel.  Exiting Setup."
	#		exit 1 
	#	else
	#		if ! [[ "$BROADDRESS" == ?*@?*.?* ]]; then
        #			zenity --error --title "$TITLE" --text="Please provide a valid response\!"
        #		else
	#			[ $DEBUG -eq 1 ] && echo "DEBUG: Clicked OK.  Configuring notification address for Bro."
	#			BRO_CONFIRMED="yes"
        #		fi
	#	fi
	#done
fi
#########################################
# Sguil email
#########################################
TEXT="Would you like to configure email alerts for Sguil?"
YES="Yes"
NO="No"
zenity --question --title="$TITLE" --text="$TEXT" --ok-label="$YES" --cancel-label="$NO" --no-wrap
ANSWER="$?"
if [ $ANSWER -eq 1 ]; then
        [ $DEBUG -eq 1 ] && echo "DEBUG: Clicked No.  Not configuring email for Sguil."
	SGUILADDRESS="Not Configured"
else
        [ $DEBUG -eq 1 ] && echo "DEBUG: Clicked Yes.  Configuring email for Sguil."
	#########################################
        # Sguil email address
        #########################################
        SGUIL_CONFIRMED="yes"
	SGUILADDRESS="root@localhost"
	#while [ $SGUIL_CONFIRMED = "no" ]; do
	#	TEXT="Would email address would you like to use for Sguil alerts?"
	#	SGUILADDRESS=`zenity --title="$TITLE" --text="$TEXT" --entry --entry-text="$NOTIFYADDRESS"`
        #	ANSWER="$?"
	#	if [ $ANSWER -eq 1 ]; then
	#		[ $DEBUG -eq 1 ] && echo "DEBUG: Clicked Cancel.  Exiting Setup."
	#		exit 1
	#	else
  	#
	#		if ! [[ "$SGUILADDRESS" == ?*@?*.?* ]]; then
	#			zenity --error --title "$TITLE" --text="Please provide a valid response\!"
	#		else
	#			[ $DEBUG -eq 1 ] && echo "DEBUG: Clicked OK.  Configuring notification address for Sguil."
	#			SGUIL_CONFIRMED="yes"
	#		fi
	#	fi
	#done 
fi
#########################################
# OSSEC email
#########################################
TEXT="Would you like to configure email alerts for OSSEC?"
YES="Yes"
NO="No"
zenity --question --title="$TITLE" --text="$TEXT" --ok-label="$YES" --cancel-label="$NO" --no-wrap
ANSWER="$?"
if [ $ANSWER -eq 1 ]; then
        [ $DEBUG -eq 1 ] && echo "DEBUG: Clicked No.  Not configuring email for OSSEC."
	OSSECADDRESS="Not Configured"
else
        [ $DEBUG -eq 1 ] && echo "DEBUG: Clicked Yes.  Configuring email for OSSEC."
	#########################################
        # OSSEC email address
        #########################################
        OSSEC_CONFIRMED="yes"
	OSSECADDRESS="root@localhost"
	#while [ $OSSEC_CONFIRMED = "no" ]; do
	#	TEXT="Would email address would you like to use for OSSEC alerts?"
	#	OSSECADDRESS=`zenity --title="$TITLE" --text="$TEXT" --entry --entry-text="$NOTIFYADDRESS"`
        #	ANSWER="$?"
	#	if [ $ANSWER -eq 1 ]; then 
	#		[ $DEBUG -eq 1 ] && echo "DEBUG: Clicked Cancel.  Exiting Setup."
	#		exit 1
	#	else	
	#		if ! [[ "$OSSECADDRESS" == ?*@?*.?* ]]; then
	#			zenity --error --title "$TITLE" --text="Please provide a valid response\!"
	#		else
	#			[ $DEBUG -eq 1 ] && echo "DEBUG: Clicked OK.  Configuring notification address for OSSEC."
	#			OSSEC_CONFIRMED="yes"
	#		fi
	#	fi
	#done
fi
#########################################
#ELSA email
#########################################
TEXT="Would you like to configure email alerts for ELSA?"
YES="Yes"
NO="No"
zenity --question --title="$TITLE" --text="$TEXT" --ok-label="$YES" --cancel-label="$NO" --no-wrap
ANSWER="$?"
if [ $ANSWER -eq 1 ]; then
        [ $DEBUG -eq 1 ] && echo "DEBUG: Clicked No.  Not configuring email for ELSA."
	ELSAADDRESS="Not Configured"
else
        [ $DEBUG -eq 1 ] && echo "DEBUG: Clicked Yes.  Configuring email for ELSA."
	#########################################
        # ELSA email address
        #########################################
        ELSA_EMAIL_CONFIRMED="yes"
	ELSAADDRESS="root@localhost"
	#while [ $ELSA_EMAIL_CONFIRMED = "no" ]; do
	#	TEXT="Would email address would you like to use for ELSA?"
	#	ELSAADDRESS=`zenity --title="$TITLE" --text="$TEXT" --entry --entry-text="$NOTIFYADDRESS"`
        #	ANSWER="$?"
	#	if [ $ANSWER -eq 1 ]; then
	#		[ $DEBUG -eq 1 ] && echo "DEBUG: Clicked Cancel.  Exiting Setup."
	#		exit 1
	#	else	
	#		if ! [[ "$ELSAADDRESS" == ?*@?*.?* ]]; then
        #               	zenity --error --title "$TITLE" --text="Please provide a valid response\!"
        #        	else
        #                	[ $DEBUG -eq 1 ] && echo "DEBUG: Clicked OK.  Configuring notification address for ELSA."
	#			ELSA_EMAIL_CONFIRMED="yes"
        #        	fi
	#	fi
	#done
	#########################################
	# ELSA usernmae
        #########################################
        ELSA_USER_CONFIRMED="no"
	while [ $ELSA_USER_CONFIRMED = "no" ]; do	
		TEXT="What is the ELSA username to which this email address is associated?"
        	ELSAUSER=`zenity --title="$TITLE" --text="$TEXT" --entry --entry-text="$SUDO_USER"`
        	ANSWER="$?"
		if [ $ANSWER -eq 1 ]; then
			[ $DEBUG -eq 1 ] && echo "DEBUG: Clicked Cancel.  Exiting Setup."
			exit 1
		else
			if [ -z $ELSAUSER ]; then
                        	zenity --error --title "$TITLE" --text="Please provide a valid response\!"
                	else
                        	[ $DEBUG -eq 1 ] && echo "DEBUG: Clicked OK.  Configuring ELSA username."
				ELSA_USER_CONFIRMED="yes"
                	fi
		fi
        done
	#########################################
	# ELSA server IP/Hostname
        #########################################
        ELSASERVER_CONFIRMED="no"
	while [ $ELSASERVER_CONFIRMED = "no" ]; do	
		TEXT="What is the ELSA server IP/hostname for which you wish to alert?"
        	ELSASERVER=`zenity --title="$TITLE" --text="$TEXT" --entry --entry-text="$IP"`
        	ANSWER="$?"
		if [ $ANSWER -eq 1 ]; then 
			[ $DEBUG -eq 1 ] && echo "DEBUG: Clicked Cancel.  Exiting Setup."
			exit 1
		else
			if [ -z $ELSASERVER ]; then 
                        	zenity --error --title "$TITLE" --text="Please provide a valid response\!"
                	else
                        	[ $DEBUG -eq 1 ] && echo "DEBUG: Clicked OK.  Configuring ELSA server to alert upon."
				ELSASERVER_CONFIRMED="yes"
                	fi
		fi
	done
fi
if [[ $ELSAADDRESS == "Not Configured" ]]; then
	ELSAUSER="Not Configured"
	ELSASERVER="Not Configured"
fi
#########################################
# Summary
#########################################
TEXT="The following will be configured for $HOSTNAME:\n\
\n\<b>'From' address</b>: $FROMADDRESS\n\
<b>Notification address</b>: $NOTIFYADDRESS\n\
<b>Mail server</b>: $MAILSERVER\n\
<b>ELSA username</b>: $ELSAUSER\n\
<b>ELSA server</b>: $ELSASERVER\n\
\n\Please note, services will restart upon confirmation.
"
YES="Yes, Continue!"
NO="No, Quit."
zenity --question --title="$TITLE" --text="$TEXT" --ok-label="$YES" --cancel-label="$NO" --no-wrap
ANSWER="$?"
if [ $ANSWER -eq 1 ]; then
        [ $DEBUG -eq 1 ] && echo "DEBUG: Clicked No.  Exiting Setup"
	exit 1
else
        [ $DEBUG -eq 1 ] && echo "DEBUG: Clicked Yes.  Configuration confirmed."
fi

#########################################
# Begin function CONFIGURE_EMAIL
#########################################
function CONFIGURE_EMAIL() {

#Check if mailutils installed.  If not, install it.
if dpkg -l | grep -q -i "mailutils"; then
        :
else
	apt-get install -y mailutils > /dev/null 2>&1
fi

echo "10"
echo "# Configuring system mail..."
#Configure system 'notification' address
ALIASES="/etc/aliases"
if  grep -q "root:" $ALIASES;then
        sed -i "s|^root:.*$|root: $NOTIFYADDRESS|g" $ALIASES
else
        sed -i "/postmaster/a root: $NOTIFYADDRESS" $ALIASES
fi
newaliases > /dev/null 2>&1
#Configure system from address
POSTFIX="/etc/postfix/main.cf"
sed -i "s|^myhostname = .*$|myhostname = $FROMADDRESS|g" $POSTFIX
#Configure system mail server
sed -i "s|^relayhost = .*$|relayhost = $MAILSERVER|g" $POSTFIX
#Configure sostat
echo "15"
echo "# Configuring sostat mail..."
if ! [[ "$SOSTATADDRESS" == "Not Configured" ]]; then
	SOSTAT="/etc/cron.d/sostat"
	touch $SOSTAT
	echo -e '#/etc/cron.d/sostat\n#\n#crontab entry to run sostat and email its output\n\n\nSHELL=/bin/sh\nPATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin\nEMAIL=root@localhost\nHOSTNAME='$HOSTNAME'\n\n01 12 * * * root /usr/bin/sostat 2>&1 | mail -s "$HOSTNAME stats" $EMAIL' > $SOSTAT
fi
#Configure Bro
echo "30"
echo "# Configuring Bro email..."
if ! [[ "$BROADDRESS" == "Not Configured" ]]; then
	BROCTL="/opt/bro/etc/broctl.cfg"
	sed -i "s|^MailTo.*$|MailTo = $BROADDRESS|g" $BROCTL
        if  grep -q "sendmail" $BROCTL;then
        	sed -i "s|^sendmail.*$|sendmail = /usr/sbin/sendmail|g" $BROCTL
                if grep -q "tracesummary=" $BROCTL;then
                	sed -i "s|^tracesummary=.*$|tracesummary=|g" $BROCTL
                else
                	sed -i '/sendmail/a tracesummary=' $BROCTL
                fi
        else
        	sed -i '/MailTo/a\\sendmail = /usr/sbin/sendmail' $BROCTL
        fi

	LOCALBRO="/opt/bro/share/bro/site/local.bro"
        if grep -q -i "email" $LOCALBRO;then
        	:
        else
        	echo -e "\n# Bro Notice email configuration\nhook Notice::policy(n: Notice::Info)\n             {       \n      add n\$actions[Notice::ACTION_ALARM];\n         }" >> $LOCALBRO
        fi
                #echo -e "\n---------------------------------\nPlease wait while configuring...\n---------------------------------"
	nsm_sensor_ps-restart --only-bro > /dev/null
fi
#Configure Sguil
echo "45"
echo "# Configuring Sguil email..."
if ! [[ "$SGUILADDRESS" == "Not Configured" ]]; then

	SGUILDEMAIL="/etc/nsm/securityonion/sguild.email"
	sed -i "s|^set EMAIL_EVENTS.*$|set EMAIL_EVENTS 1|g" $SGUILDEMAIL
        sed -i "s|^set SMTP.*$|set SMTP_SERVER localhost|g" $SGUILDEMAIL
        sed -i "s|^set EMAIL_RCPT.*$|set EMAIL_RCPT_TO \"root@localhost\"|g" $SGUILDEMAIL
        sed -i "s|^set EMAIL_FROM.*$|set EMAIL_FROM \"$FROMADDRESS\"|g" $SGUILDEMAIL
	nsm_server_ps-restart > /dev/null
fi
#Configure OSSEC
echo "60"
echo "# Configuring OSSEC email..."
if ! [[ "$OSSECADDRESS" == "Not Configured" ]]; then
	OSSECCONF="/var/ossec/etc/ossec.conf"
        if grep -q -i "smtp" $OSSECCONF;then
		sed -i 's/.*email_notification.*/     <email_notification>yes<\/email_notification>/' $OSSECCONF
		sed -i 's/.*email_to.*/     <email_to>root@localhost<\/email_to>/' $OSSECCONF
                sed -i 's/.*smtp_server.*/     <smtp_server>localhost<\/smtp_server>/' $OSSECCONF
                sed -i 's/.*email_from.*/     <email_from>\'$HOSTNAME'\<\/email_from>/' $OSSECCONF
                sed -i 's/.*email_maxperhour.*/     <email_maxperhour>20<\/email_maxperhour>/' $OSSECCONF
        else
                sed -i 's/.*email_notification.*/     <email_notification>yes<\/email_notification>/' $OSSECCONF
                sed -i '/.*email_notification.*/ a \     <email_to>root@localhost<\/email_to>' $OSSECCONF
               	sed -i '/.*email_to.*/ a \     <smtp_server>localhost<\/smtp_server>' $OSSECCONF
                sed -i '/.*smtp_server.*/ a \     <email_from>\ossec@'$HOSTNAME'\<\/email_from>' $OSSECCONF
                sed -i '/.*email_from.*/ a \     <email_maxperhour>\100\<\/email_maxperhour>' $OSSECCONF
        fi
	service ossec-hids-server restart > /dev/null
fi
#Configure ELSA
echo "75"
echo "# Configuring ELSA email..."
if ! [[ "$ELSAADDRESS" == "Not Configured" ]]; then
	ELSAWEB="/etc/elsa_web.conf"
	mysql --defaults-file=/etc/mysql/debian.cnf -Dsecurityonion_db -e "update user_info set email='$ELSAADDRESS' where username='$ELSAUSER';"
        if grep -q -i "smtp" $ELSAWEB;then
		sed -i 's#.*display_address.*#    "display_address": "noreply@'$HOSTNAME'",#g' $ELSAWEB
		sed -i 's#.*base_url.*#    "base_url": "https://'$ELSASERVER'/elsa-query",#g' $ELSAWEB
                sed -i 's#.*smtp_server.*#    "smtp_server": "localhost"#g' $ELSAWEB
        else
		sed -i 's#.*base_url.*#    "base_url": "https://'$ELSASERVER'/elsa-query",#g' $ELSAWEB
		#sed -i '/.*"email".*/ a \    "base_url": "https://'$ELSASERVER'/elsa-query",' $ELSAWEB
                sed -i '/.*base_url.*/ a \    "smtp_server": "localhost"' $ELSAWEB
        fi
	service apache2 restart > /dev/null 2>&1
fi
}
CONFIGURE_EMAIL | zenity --progress --title="$TITLE" --text="Please wait while making changes to the system..." --percentage=0 --auto-close
########################################
# Setup Complete
########################################
TEXT="<b>Security Onion Email Setup is now complete!</b> \n \
\n \
If you would like to edit the email configuration manually, please refer to:\n
https://github.com/Security-Onion-Solutions/security-onion/wiki/Email\n"
zenity --info --title="$TITLE" --text="$TEXT" --no-wrap
